### ISSUE TITLE
unable to use package

### ISSUE THREAD

**Issue by minademian** [royriojas/prepush#13]
Unable to use this tool. I've installed both the package and the commit hook. See the following error:

<details>
<summary>TypeError: Cannot read property 'ignoreBranch' of undefined</summary>
<code>
/home/minademian/code/kivra_tenant_icons/.git/hooks/pre-push:407
  var ignoreBranch = prepushSection.ignoreBranch;
                                   ^

TypeError: Cannot read property 'ignoreBranch' of undefined
    at ignoreBranchFn (/home/minademian/code/_icons/.git/hooks/pre-push:407:36)
    at /home/minademian/code/_icons/.git/hooks/pre-push:442:10
    at /home/minademian/code/_icons/.git/hooks/pre-push:223:13
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
error: failed to push some refs to <git repo>
</code>
</details>

**Comment by royriojas** [comment]
hi @minademian, thanks for reporting the issue

A couple of questions: 

- Is your `.git` folder at the same level of your `node_modules`?
- what node version are you using?

Also I know is not always easy, but, can you provide a small repo where this issue happens?

**Comment by minademian** [comment]
appreciate your response!

yes, on the same level.
v6.11.0

alright, let me see if I can do that, haven't done it before. :)
